//! File templates for `gansi new`. Tokens `{{name}}`, `{{name_snake}}`
//! and `{{title}}` are substituted by [`render`].

use crate::project::Project;

pub fn render(template: &str, project: &Project) -> String {
    template
        .replace("{{name}}", &project.name)
        .replace("{{name_snake}}", &project.name_snake)
        .replace("{{title}}", &project.title)
}

pub fn render_local(template: &str, project: &Project) -> String {
    let rendered = render(template, project);
    match &project.local_yse {
        Some(path) => rendered.replace("{{yse_path}}", path),
        None => rendered,
    }
}

/// Facade-based template: depends on a local Yse checkout and needs no C++
/// shim of its own.
pub const CARGO_TOML_LOCAL: &str = r#"# Generated by gansi new --local.
[package]
name = "{{name}}"
version = "0.1.0"
edition = "2024"

[dependencies]
yse = { path = "{{yse_path}}/crates/yse" }
"#;

pub const MAIN_RS_LOCAL: &str = r#"// Generated by gansi new --local.
use yse::*;

fn main() {
    let app = Application::init();
    let window = Window::new();
    window.set_title("{{title}}");
    window.set_size(320, 140);
    let column = window.column();

    let count = Var::new(0u32);
    let label = column.label("Count: 0");
    label.bind_text(&count.signal().map(|c| format!("Count: {c}")));

    let button = column.button("Increment");
    let count_rc = count.clone();
    let _sub = button.clicked().observe(move |_| {
        let next = *count_rc.value() + 1;
        count_rc.set(next);
    });

    if std::env::var("YSE_SMOKE").is_ok() {
        button.click();
        app.quit_after(300);
    }

    window.show();
    let code = app.exec();
    println!("count={}", count.value());
    std::process::exit(code);
}
"#;

pub const CARGO_TOML: &str = r#"# Generated by gansi new.
[package]
name = "{{name}}"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1"
cxx-qt = "0.9"
cxx-qt-lib = { version = "0.9", features = ["qt_gui"] }

[build-dependencies]
cxx-qt-build = "0.9"
"#;

pub const BUILD_RS: &str = r#"// Generated by gansi new.
fn main() {
    cxx_qt_build::CxxQtBuilder::new()
        .file("src/bridge.rs")
        .cpp_file("src/spike.cpp")
        .qt_module("Gui")
        .qt_module("Widgets")
        .build();
}
"#;

pub const YSE_TOML: &str = r#"# Yse project configuration. The Qt version, compiler
# family, and target architecture are pinned here for reproducible builds.
[project]
name = "{{name}}"
qt_version = "6.8"
compiler_family = "gcc"   # gcc | msvc | clang
target_arch = "x86_64"

[deployment]
bundle_name = "{{title}}"
"#;

pub const GITIGNORE: &str = r#"/target
/dist
"#;

pub const ICON_SVG: &str = r##"<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128">
  <rect width="128" height="128" rx="20" fill="#1f6feb"/>
  <text x="64" y="84" font-family="sans-serif" font-size="56" font-weight="bold" fill="#ffffff" text-anchor="middle">Y</text>
</svg>
"##;

pub const MAIN_RS: &str = r#"// Generated by gansi new.
mod bridge;

// cxx-qt-lib is not used directly by this template, but CXX-Qt's crate
// initialisation chain requires its native library to be linked.
#[allow(unused_extern_crates)]
extern crate cxx_qt_lib;

fn main() {
    let code = bridge::qobject::run_app();
    std::process::exit(code);
}
"#;

pub const BRIDGE_RS: &str = r#"// Generated by gansi new. The Rust side of the app:
// a small QObject that owns the counter state.
use cxx_qt::CxxQtType;
use std::pin::Pin;

#[cxx_qt::bridge(namespace = "{{name_snake}}")]
pub mod qobject {
    #[namespace = ""]
    unsafe extern "C++" {
        include!("{{name}}/src/spike.h");

        /// Run the application; blocks in the Qt event loop.
        fn run_app() -> i32;
    }

    extern "RustQt" {
        #[qobject]
        #[qproperty(u32, count)]
        type Counter = super::CounterRust;

        #[qinvokable]
        #[cxx_name = "incrementCount"]
        fn increment_count(self: Pin<&mut Self>);
    }
}

pub struct CounterRust {
    pub count: u32,
}

impl Default for CounterRust {
    fn default() -> Self {
        Self { count: 0 }
    }
}

impl qobject::Counter {
    pub fn increment_count(mut self: Pin<&mut Self>) {
        let next = self.as_mut().rust_mut().count + 1;
        self.as_mut().set_count(next);
    }
}
"#;

pub const SPIKE_H: &str = r#"// Generated by gansi new. The only hand-written C++
// surface the Rust side sees.
#pragma once
int run_app() noexcept;
"#;

pub const SPIKE_CPP: &str = r#"// Generated by gansi new. The C++ shim owns the raw
// Qt Widgets surface; Rust owns the reactive state.

#include "{{name}}/src/spike.h"

#include <QApplication>
#include <QLabel>
#include <QPushButton>
#include <QTimer>
#include <QVBoxLayout>
#include <QWidget>

#include "{{name}}/src/bridge.cxxqt.h"

int run_app() noexcept
{
  int argc = 1;
  static const char arg0[] = "{{name}}";
  char* argv[] = { const_cast<char*>(arg0), nullptr };
  QApplication app(argc, argv);

  QWidget window;
  window.setWindowTitle(QStringLiteral("{{title}}"));
  window.resize(320, 140);
  auto* layout = new QVBoxLayout(&window);
  auto* label = new QLabel(QStringLiteral("Count: 0"), &window);
  auto* button = new QPushButton(QStringLiteral("Increment"), &window);
  layout->addWidget(label);
  layout->addWidget(button);

  {{name_snake}}::Counter counter(&window);
  QObject::connect(button, &QPushButton::clicked, &counter, [&counter] {
    counter.incrementCount();
  });
  QObject::connect(&counter, &{{name_snake}}::Counter::countChanged, &window, [label, &counter] {
    label->setText(
      QStringLiteral("Count: %1").arg(static_cast<qlonglong>(counter.getCount())));
  });

  window.show();

  if (qEnvironmentVariableIsSet("YSE_SMOKE")) {
    QTimer::singleShot(100, &app, [&] { button->click(); });
    QTimer::singleShot(300, &app, [&] { app.quit(); });
  }

  return app.exec();
}
"#;

pub const RELEASE_MD: &str = r#"# Release guide for {{title}}

`gansi bundle` builds a release binary and lays it out in `dist/{{name}}/`.
On Linux that is a portable binary (Qt must be present on the target or
deployed alongside it); on Windows `windeployqt` and on macOS `macdeployqt`
are invoked automatically when available.

## What remains application-specific

These steps cannot be automated generically and are your responsibility:

- **Code signing** — Windows Authenticode and macOS Developer ID signing
  require your certificates and credentials.
- **macOS notarization** — `xcrun notarytool` submission and stapling need
  an App Store Connect account.
- **Store submissions** — Microsoft Store / App Store / Sparkle packaging.
- **Third-party native dependencies** — any libraries beyond Qt must be
  bundled and licensed manually.

## Checklist

1. `gansi test`
2. `gansi bundle`
3. Inspect `dist/{{name}}/` and run the app on a clean machine.
4. Sign and notarize per platform; submit where applicable.
"#;
